from classifTools import txt_animalclasses

trapper_2_categories = [
  "Domestic Cat",
  "Eurasian Magpie",
  "Mountain Hare",
  "Chaffinch",
  "Brambling",
  "Eurasian Red Squirrel",
  "Western Jackdaw",
  "European Badger",
  "Great Tit",
  "Common Blackbird",
  "Roe Deer",
  "Eurasian Tree Sparrow",
  "Eurasian Blue Tit",
  "Domestic Dog",
  "Red Fox",
  "Chicken",
  "Fieldfare",
  "Hooded Crow",
  "Domestic Rabbit",
  "Song Thrush",
  "Greylag Goose",
  "White Wagtail",
  "Eurasian Oystercatcher",
  "Common wood pigeon",
  "Common Gull",
  "Other",
  "Dunnock",
  "Eurasian Woodcock",
  "Redwing",
  "West European Hedgehog",
  "Black-headed Gull",
  "Common Crane",
  "Eurasian Elk",
  "Mistle Thrush",
  "European Robin",
  "Spotted Nutcracker"
]

deepfaune_categories = txt_animalclasses

# a very rough mapping from the deepfaune categories to the trapper categories
deepfaune_prediction2trapper = {
    "bison": "Other",
    "badger": "European Badger",
    "ibex": "Other",
    "beaver": "Other",
    "red deer": "Red Deer",
    "chamois": "Other",
    "cat": "Domestic Cat",
    "goat": "Other",
    "roe deer": "Roe Deer",
    "dog": "Domestic Dog",
    "fallow deer": "Other",
    "squirrel": "Eurasian Red Squirrel",
    "moose": "Eurasian Elk",
    "equid": "Other",
    "genet": "Other",
    "wolverine": "Other",
    "hedgehog": "West European Hedgehog",
    "lagomorph": "Mountain Hare",
    "wolf": "Other",
    "otter": "Other",
    "lynx": "Other",
    "marmot": "Other",
    "micromammal": "Other",
    "mouflon": "Other",
    "sheep": "Other",
    "mustelid": "European Badger",
    "bird": "Common Blackbird",
    "bear": "Other",
    "nutria": "Other",
    "raccoon": "Other",
    "fox": "Red Fox",
    "reindeer": "Reindeer",
    "wild boar": "Wild Boar",
    "cow": "Other"
}

