# Copyright CNRS 2022

# simon.chamaille@cefe.cnrs.fr; vincent.miele@univ-lyon1.fr

# This software is a computer program whose purpose is to identify
# animal species in camera trap images.

#This software is governed by the CeCILL  license under French law and
# abiding by the rules of distribution of free software.  You can  use, 
# modify and/ or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and INRIA at the following URL
# "http://www.cecill.info". 

# As a counterpart to the access to the source code and  rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty  and the software's author,  the holder of the
# economic rights,  and the successive licensors  have only  limited
# liability. 

# In this respect, the user's attention is drawn to the risks associated
# with loading,  using,  modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean  that it is complicated to manipulate,  and  that  also
# therefore means  that it is reserved for developers  and  experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards their
# requirements in conditions enabling the security of their systems and/or 
# data to be ensured and,  more generally, to use and operate it in the 
# same conditions as regards security. 

# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.

####################################################################################
### LOADING YOLO
####################################################################################
import cv2
import numpy as np
import torch
from PIL import Image

YOLO_SIZE=1280
model = 'deepfaune-yolov4.weights'
config = 'deepfaune-yolov4.cfg'

####################################################################################
### BEST BOX DETECTION 
####################################################################################
class Detector:
    
    def __init__(self):
        self.yolo = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5_last.pt')


    """
    :param image: image in BGR loaded by opencv
    :param threshold : above threshold, keep the best box given
    """
    def bestBoxDetection(self, image, threshold=0.5):
        '''
        in/out as numpy int array (0-255) in BGR
        '''
        croppedimage = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(croppedimage)
        results = self.yolo(image, size=YOLO_SIZE)

        detections = results.pandas().xyxy[0]

        if not len(detections):
            return [], 0

        detection = detections.iloc[0]
        score = float(detection['confidence'])
        if score >= threshold:
            ret_images = image.crop((detection['xmin'], detection['ymin'], detection['xmax'],detection['ymax']))
            categories = detection['class'] + 1
            return ret_images, int(categories)
        else:
            return [], 0


####################################################################################
### BEST BOX DETECTION WITH JSON
####################################################################################

from load_api_results import load_api_results
import contextlib
import os
from pandas import concat
from numpy import argmax

class DetectorJSON:
    
    """
    We assume JSON categories are 1=animal, 2=person, 3=vehicle and the empty category 0=empty

    :param jsonfilename: JSON file containing the bondoing boxes coordinates, such as generated by megadetectorv5
    :param threshold : above threshold, keep the best box
    """
    def __init__(self, jsonfilename, threshold=0.5):
        # getting results in a dataframe
        with contextlib.redirect_stdout(open(os.devnull, 'w')):
            self.df_json, _ = load_api_results(jsonfilename)
            # removing lines with Failure event
            if 'failure' in self.df_json.keys():
                self.df_json = self.df_json[self.df_json['failure'].isnull()]
                self.df_json.reset_index(drop=True, inplace = True)
                self.df_json.drop('failure', axis=1, inplace=True)
        self.threshold = threshold
        self.k = 0 # current image index
        self.kbox = 0 # current box index

    def nextBestBoxDetection(self):
        if len(self.df_json['detections'][self.k]): # is non empty
            # Focus on the most confident bounding box coordinates
            self.kbox = argmax([box['conf'] for box in self.df_json['detections'][self.k]])
            if self.df_json['detections'][self.k][self.kbox]['conf']>self.threshold:
                category = int(self.df_json['detections'][self.k][self.kbox]['category'])
            else:
                category = 0
        else: # is empty
            category = 0
        # is an animal detected ?
        if category != 1:
            croppedimage = []
        # if yes, cropping the bounding box
        else:
            croppedimage = self.cropBox()
        # goto next image
        self.k += 1
        return croppedimage, category

    def nextBoxDetection(self):
        if self.k >= len(self.df_json):
            raise IndexError # no next box
        # is an animal detected ?
        if len(self.df_json['detections'][self.k]):
            # is box above threshold ?
            if self.df_json['detections'][self.k][self.kbox]['conf']>self.threshold:
                category = int(self.df_json['detections'][self.k][self.kbox]['category'])
                croppedimage = self.cropBox()
            else: # considered as empty
                category = 0
                croppedimage = []
            self.kbox += 1
            if self.kbox >= len(self.df_json['detections'][self.k]):
                self.k += 1
                self.kbox = 0
        else: # is empty
            category = 0
            croppedimage = []
            self.k += 1
            self.kbox = 0
        return croppedimage, category
          
    def cropBox(self):
        image_path = str(self.df_json["file"][self.k])
        image = cv2.imread(image_path)
        if image is None:
            return []
        bbox_norm = self.df_json['detections'][self.k][self.kbox]["bbox"]
        img_h, img_w = image.shape[:2]
        xmin = int(bbox_norm[0] * img_w)
        ymin = int(bbox_norm[1] * img_h)
        box_w = int(bbox_norm[2] * img_w)
        box_h = int(bbox_norm[3] * img_h)
        box_size = max(box_w, box_h)
        xmin = max(0, min(xmin - int((box_size - box_w) / 2),img_w - box_w))
        ymin = max(0, min(ymin - int((box_size - box_h) / 2),img_h - box_h))
        box_w = min(img_w, box_size)
        box_h = min(img_h, box_size)
        croppedimage = image[max(0,ymin):min(img_h,ymin + box_h),
                             max(0,xmin):min(img_w,xmin + box_w)]
        return croppedimage
        
    def getNbFiles(self):
        return self.df_json.shape[0]
    
    def getFilenames(self):
        return list(self.df_json["file"].to_numpy())
    
    def getCurrentFilename(self):
        if self.k >= len(self.df_json):
            raise IndexError
        return self.df_json['file'][self.k]
    
    def resetDetection(self):
        self.k = 0
        self.kbox = 0
    
    def merge(self, detector):
        self.df_json = concat([self.df_json, detector.df_json], ignore_index=True)
        self.resetDetection()
