# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


    - name: Cache deepfaune-yolov8s_960.pt
      uses: actions/cache@v3
      with:
        path: deepfaune-yolov8s_960.pt
        key: deepfaune-yolov8s_960-${{ runner.os }}

    - name: Cache deepfaune-vit_large_patch14_dinov2.lvd142m.v3.pt
      uses: actions/cache@v3
      with:
        path: deepfaune-vit_large_patch14_dinov2.lvd142m.v3.pt
        key: deepfaune-vit_large-${{ runner.os }}

    - name: Download Models if Not Cached
      run: |
        if [ ! -f deepfaune-yolov8s_960.pt ]; then
          echo "Downloading deepfaune-yolov8s_960.pt..."
          wget -q -O deepfaune-yolov8s_960.pt https://pbil.univ-lyon1.fr/software/download/deepfaune/v1.2/deepfaune-yolov8s_960.pt
        else
          echo "deepfaune-yolov8s_960.pt found in cache."
        fi
        
        if [ ! -f deepfaune-vit_large_patch14_dinov2.lvd142m.v3.pt ]; then
          echo "Downloading deepfaune-vit_large_patch14_dinov2.lvd142m.v3.pt..."
          wget -q -O deepfaune-vit_large_patch14_dinov2.lvd142m.v3.pt https://pbil.univ-lyon1.fr/software/download/deepfaune/v1.3/deepfaune-vit_large_patch14_dinov2.lvd142m.v3.pt
        else
          echo "deepfaune-vit_large_patch14_dinov2.lvd142m.v3.pt found in cache."
        fi

    - name: Test with pytest
      run: |
        PYTHONPATH=./:PYTHONPATH pytest tests

